name: Analyse Terraform avec TFDefectGA 🚀

on:
  push:
    paths:
      - "**.tf"
  pull_request:
    paths:
      - "**.tf"
  workflow_dispatch:

jobs:
  tfdefect-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner un commit précis
        uses: actions/checkout@v3
        with:
          ref: c191f7bcb0fa786b68c7b3904b6f3bbb90881fc6
          fetch-depth: 0

      - name: 🚀 Lancer TFDefectGA
        uses: TFDefect/TFDefectGA@v1.0.3
        with:
          model: randomforest

      - name: 📦 Sauvegarder le rapport HTML
        uses: actions/upload-artifact@v4
        with:
          name: rapport-tfdefectga
          path: out/reports/*.html

      - name: 💾 Sauvegarder defect_history.json
        uses: actions/upload-artifact@v4
        with:
          name: historique-defauts
          path: out/defect_history.json
